frequency: 50
odom_frame: odom
base_link_frame: base_link
world_frame: odom
predict_to_current_time: false
two_d_mode: true
#use_control: true
#control_config: [true,  false, false,
#                 false, false, true]
print_diagnostics: true
publish_tf: true

#[x_pos   , y_pos    , z_pos,
# roll    , pitch    , yaw,
# x_vel   , y_vel    , z_vel,
# roll_vel, pitch_vel, yaw_vel,
# x_accel , y_accel  , z_accel]


odom0: /mobile_base_controller/odom
odom0_config: [true,  true,  true,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false]
odom0_differential: true
odom0_relative: true


imu0: /bno085/imu
imu0_config: [false,  false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]

imu0_differential: false
imu0_relative: true
imu0_remove_gravitational_acceleration: true
