frequency: 50
odom_frame: odom
base_link_frame: base_link
world_frame: odom
predict_to_current_time: false
two_d_mode: false
#use_control: true
#control_config: [true,  false, false,
#                 false, false, true]
print_diagnostics: true
publish_tf: true

#[x_pos   , y_pos    , z_pos,
# roll    , pitch    , yaw,
# x_vel   , y_vel    , z_vel,
# roll_vel, pitch_vel, yaw_vel,
# x_accel , y_accel  , z_accel]




odom0: /mobile_base_controller/odom
odom0_config: [true,  true,  true,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false]
odom0_differential: false
odom0_relative: false



imu0: /bno085/imu
imu0_config: [false,  false, false,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]

imu0_differential: false
imu0_relative: false
imu0_remove_gravitational_acceleration: true

#imu0_differential: false
#imu0_relative: false
#imu0_remove_gravitational_acceleration: false

#imu1: /imu
#imu1_config: [false,  false, false,
#              false, false, false,
#              false, false, false,
#              false, false, true,
#              false, false, false]
#
#imu1_differential: false
#imu1_relative: false
#imu1_remove_gravitational_acceleration: true

#dynamic_process_noise_covariance: true
#
## [ADVANCED] The process noise covariance matrix can be difficult to tune, and can vary for each application, so it is
## exposed as a configuration parameter. This matrix represents the noise we add to the total error after each
## prediction step. The better the omnidirectional motion model matches your system, the smaller these values can be.
## However, if users find that a given variable is slow to converge, one approach is to increase the
## process_noise_covariance diagonal value for the variable in question, which will cause the filter's predicted error
## to be larger, which will cause the filter to trust the incoming measurement more during correction. The values are
## ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Defaults to the matrix below if
## unspecified.
#process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
#                           0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]
#
## [ADVANCED] This represents the initial value for the state estimate error covariance matrix. Setting a diagonal
## value (variance) to a large value will result in rapid convergence for initial measurements of the variable in
## question. Users should take care not to use large values for variables that will not be measured directly. The values
## are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Defaults to the matrix below
##if unspecified.
#initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
#                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]