frequency: 30
odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: map
predict_to_current_time: true
two_d_mode: false
#smooth_lagged_data: true
print_diagnostics: true
publish_tf: true
disabled_at_startup: false

#[x_pos   , y_pos    , z_pos,
# roll    , pitch    , yaw,
# x_vel   , y_vel    , z_vel,
# roll_vel, pitch_vel, yaw_vel,
# x_accel , y_accel  , z_accel]

odom0: /odometry/gps
odom0_config: [true,  true,  true,   # x,   y,   z
               false, false, false,   # r,   p,   w (yaw)
               false, false, false,   # dx,  dy,  dz
               false, false, false,   # dr,  dp,  dw
               false, false, false]   # ddx, ddy, ddz
odom0_differential: false
odom0_queue_size: 200

odom1: /mobile_base_controller/odom
odom1_config: [false, false, false,   # x,   y,   z
               false, false, false,   # r,   p,   w (yaw)
               true,  true,  true,    # dx,  dy,  dz
               false, false, true,    # dr,  dp,  dw
               false, false, false]   # ddx, ddy, ddz
odom1_differential: true
odom1_queue_size: 200



imu1: /gnss_heading/navheading
imu1_config: [false, false, false,
              false,  false,  true,
              false, false, false,
              false,  false,  false,
              false,  false,  false]
#imu1_nodelay: false
imu1_differential: false
#imu1_relative: false
imu1_queue_size: 200

#imu1: /bno085/imu
#imu1_config: [false, false, false,   # x,   y,   z
#              true,  true,  true,    # r,   p,   w (yaw)
#              false, false, false,   # dx,  dy,  dz
#              true,  true,  true,    # dr,  dp,  dw
#              true,  true,  true,]   # ddx, ddy, ddz
#imu1_differential: false
#imu1_relative: false
#imu1_queue_size: 200
#imu1_remove_gravitational_acceleration: true

imu0: /bno085/navheading
imu0_config: [false, false, false,   # x,   y,   z
              true,  true,  false,    # r,   p,   w (yaw)
              false, false, false,   # dx,  dy,  dz
              true,  true,  true,    # dr,  dp,  dw
              true,  true,  true,]   # ddx, ddy, ddz
imu0_differential: false
imu0_queue_size: 200
imu0_remove_gravitational_acceleration: true



dynamic_process_noise_covariance: false

initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]