frequency: 50
odom_frame: odom
base_link_frame: base_link
world_frame: odom
predict_to_current_time: true
two_d_mode: false

print_diagnostics: true
publish_tf: true

#[x_pos   , y_pos    , z_pos,
# roll    , pitch    , yaw,
# x_vel   , y_vel    , z_vel,
# roll_vel, pitch_vel, yaw_vel,
# x_accel , y_accel  , z_accel]

############ Wheels

odom0: /mobile_base_controller/odom
odom0_config: [false, false, true,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false
#odom0_relative: false

########## T265

#odom1: /t265/odom/sample
#odom1_config: [true, true, true,
#               true, true, true,
#               false, false, false,
#               false, false, false,
#               false, false, false]
#odom1_differential: true

#odom1_config: [false, false, false,
#               false, false, false,
#               true, true, true,
#               true, true, true,
#               false, false, false]
#odom1_differential: true

##########  OPENCR IMU

imu0: /imu
imu0_config: [false,  false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              false, false, false]

imu0_differential: true
#imu0_relative: false
imu0_remove_gravitational_acceleration: true

