ekf_navsat:
  frequency: 50
  two_d_mode: false
  print_diagnostics: true
  publish_tf: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /odometry/gps
  odom0_config: [ true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false ]
  odom0_differential: false
  odom0_relative: false

  imu0: /gnss/navheading
  imu0_config: [ false,  false, false,
                 false, false, true,
                 false, false, false,
                 false, false, false,
                 false, false, false ]

  imu0_differential: false
  imu0_relative: false
  imu0_remove_gravitational_acceleration: false
