frequency: 10
delay: 5.0
magnetic_declination_radians: 0
#magnetic_declination_radians: 0.0846 # weekend house
#yaw_offset: 0.0
zero_altitude: false
broadcast_utm_transform: true
broadcast_utm_transform_as_parent_frame: false
publish_filtered_gps: true
#yaw_offset: -3,1415926
#yaw_offset: -1.5707963
#yaw_offset: 1.5707963
yaw_offset: 0
use_odometry_yaw: false

wait_for_datum: false
#datum: [50.018686, 14.903361, 349.947000, map, base_link]