
############################################## NAVSAT  ##############################################

navsat_transform:
  frequency: 10
  delay: 5.0
  magnetic_declination_radians: 0
  zero_altitude: false
  broadcast_cartesian_transform: true
  broadcast_cartesian_transform_as_parent_frame: false
  publish_filtered_gps: true
  yaw_offset: 0
  use_odometry_yaw: true
  wait_for_datum: false