map_frame_id:                               map
robot_base_frame_id:                        base_link
robot_pose_with_covariance_topic:           /pose_cov_stamped
robot_pose_cache_size:                      200
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
#    topic: /voxel_grid/output_z
    topic: /cloudXYZ
    queue_size: 1
    publish_on_update: true # Wheter to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      cutoff_min_depth: 0.25
      cutoff_max_depth: 3.25
      ignore_points_above:       0.5
track_point_frame_id:                       base_link
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0
min_update_rate:                            6.0
time_tolerance:                             1.0
time_offset_for_point_cloud:                0.00
#sensor_processor/ignore_points_above:       0.5
robot_motion_map_update/covariance_scale:   0.01


##point_cloud_topic: "/voxel_grid/output_z"
#input_sources:
#    camera: # A name to identify the input source
#        type: pointcloud # Supported types: pointcloud
#        topic: /voxel_grid/output_z_light # your topic
##        topic: /voxel_grid/output_z # your topic
#        queue_size: 1
#        publish_on_update: true
#        sensor_processor:
#    #        ignore_points_above: .inf
#    #        ignore_points_below: -.inf
#            cutoff_min_depth: 0.25
#            cutoff_max_depth: 2.5
#            type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
#            normal_factor_a: 0.001063
#            normal_factor_b:  0.003949
#            normal_factor_c: 0.0
#            normal_factor_d: 0.0008278
#            normal_factor_e: 1
#            lateral_factor: 0.01576 # approx 1 deg
##point_cloud_topic: <value>/voxel_grid/output_z</value>
##point_cloud_topic: "/camera/depth/color/points"
##map_frame_id: odom
#map_frame_id: map
#robot_base_frame_id: base_link
#robot_pose_with_covariance_topic: /pose_cov_stamped
#robot_pose_cache_size: 200
#track_point_frame_id: base_link
#track_point_x: 0.0
#track_point_y: 0.0
#track_point_z: 0.0
#sensor_frame_id: camera_depth_optical_frame
##sensor_processor/apply_voxelgrid_filter: true
##sensor_processor/voxelgrid_filter_size: 0.05

