TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0

  holonomic_robot: false
  meter_scoring: true

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1


