TebLocalPlannerROS:

# odom_topic: /odometry/filtered/map
 odom_topic: /odometry/odom
 map_frame: map

# map_frame: t265_odom_frame

 # Trajectory

 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5

 # Robot

 max_vel_x: 0.5 # Vitulus max is 0,42332961 m/s, for slow use 0.1, for fast use 0.42
 max_vel_x_backwards: 0.5 # Vitulus max is 0,42332961 m/s, for slow use 0.05, for fast use 0.42
 max_vel_theta: 1.2 #  0.75   Vitulus max is 1,801402596 rad/s, for slow use 0.1, for fast use 5.0 1.8
 acc_lim_x: 0.5 # 1.5     0.5
 acc_lim_theta: 1.0 # 2.0     0.5,  5.0
 min_turning_radius: 0.0 # 0.6
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
#   radius: 0.36 # for type "circular"
#   vertices: [[0.10, -0.256], [0.10, 0.256], [-0.10, 0.256], [-0.10, 0.10], [-0.55, 0.10], [-0.55, -0.10], [-0.10, -0.10], [-0.10, -0.256] ] # for type "polygon"
#   vertices: [[-0.03,-0.256],[-0.03,0.256],[-0.55,0.256],[-0.55,0.05],[-0.6,0.05],[-0.6,-0.05],[-0.55,-0.05],[-0.55,-0.256]] # for type "polygon"
   vertices: [[0.238,-0.256],[0.238,0.256],[-0.238,0.256],[-0.238,0.050],[-0.288,0.05],[-0.288,-0.05],[-0.238,-0.05],[-0.238,-0.256]]  # 4WD
#   vertices: [[0.25,-0.256],[0.25,0.256],[-0.25,0.256],[-0.25,0.05],[-0.3,0.05],[-0.3,-0.05],[-0.25,-0.05],[-0.25,-0.256]]   ## 4WD Long
#   vertices: [[0.01,-0.256],[0.01,0.256],[-0.51,0.256],[-0.51,0.05],[-0.56,0.05],[-0.56,-0.05],[-0.51,-0.05],[-0.51,-0.256]]
 # GoalTolerance

 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.2
 free_goal_vel: true

 # Via points
 global_plan_viapoint_sep: 0.2


 # Obstacles

 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization

 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.005 # 0.1 , 0.04
 weight_max_vel_x: 1
 weight_max_vel_y: 0
 weight_max_vel_theta: 1
 weight_acc_lim_x: 2
 weight_acc_lim_y: 0
 weight_acc_lim_theta: 10 # 2
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 500
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 70  # 1
 weight_obstacle: 10  # 50
 weight_viapoint: 440  # nebylo
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False


