
controllers:
#  - name: GracefulControllerROS
#    type: graceful_controller/GracefulControllerROS
#  - name: NeoLocalPlanner
#    type: neo_local_planner/NeoLocalPlanner
#  - name: DWAPlannerROS
#    type: dwa_local_planner/DWAPlannerROS
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS
  - name: TrajectoryPlannerROS
    type: base_local_planner/TrajectoryPlannerROS




controller_frequency: 30.0
controller_patience: 6.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

