local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 6.0
  static_map: false
  rolling_window: true
  always_send_full_costmap: true
  transform_tolerance: 1.0
  width: 4.0
  height: 4.0
  resolution: 0.05  # 0.02



  plugins:
    - {name: base_static_layer, type: "costmap_2d::StaticLayer"}
    - {name: cloud_costmap_layer, type: "costmap_2d::StaticLayer"}
    - {name: lidar_costmap_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}



  laser_layer:
    #  enabled: true
    combination_method: 1  # 1=max, 0=override
    observation_sources: laser_scan
    track_unknown_space: false

    laser_scan: 
      data_type: LaserScan
      topic: /rplidar/scan_5m
      marking: true
      clearing: true
      observation_persistence: 0.0
      expected_update_rate: 10.0
      obstacle_range: 1.9
      raytrace_range: 6.0
      min_obstacle_height: 0.0
      max_obstacle_height: 0.4
      inf_is_valid: true


  lidar_costmap_layer:
    map_topic: /local_costmap/lidar_map
    subscribe_to_updates: true
    track_unknown_space: false
    use_maximum: true

  base_static_layer:
    map_topic: /navi_manager/map
    subscribe_to_updates: true
    track_unknown_space: false
    use_maximum: false

  cloud_costmap_layer:
    map_topic: /local_costmap/cloud_map
    subscribe_to_updates: true
    track_unknown_space: false
    use_maximum: true

