

planners:
#  - name: NavfnROS
#    type: navfn/NavfnROS
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

#planners:
#  - name: SBPLLatticePlanner
#    type: SBPLLatticePlanner

controllers:
#  - name: GracefulControllerROS
#    type: graceful_controller/GracefulControllerROS
#  - name: NeoLocalPlanner
#    type: neo_local_planner/NeoLocalPlanner
#  - name: DWAPlannerROS
#    type: dwa_local_planner/DWAPlannerROS
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS
  - name: TrajectoryPlannerROS
    type: base_local_planner/TrajectoryPlannerROS




controller_frequency: 30.0
controller_patience: 6.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

#planners:
#  - name: CarrotPlanner
#    type: carrot_planner/CarrotPlanner

#planners:
#  - name: NavfnROS
#    type: navfn/NavfnROS



