
#planners:
#  - name: GlobalPlanner
#    type: global_planner/GlobalPlanner

planners:
  - name: SBPLLatticePlanner
    type: SBPLLatticePlanner

controllers:
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS

controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

#planners:
#  - name: CarrotPlanner
#    type: carrot_planner/CarrotPlanner

#planners:
#  - name: NavfnROS
#    type: navfn/NavfnROS



