
planners:
#  - name: NavfnROS
#    type: navfn/NavfnROS
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner
#  - name: SBPLLatticePlanner
#    type: SBPLLatticePlanner

planner_frequency: 1.0
planner_patience: 5.0


