recovery_behaviors:
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

clear_costmap:
  reset_distance: 0.0
  force_updating: true
  affected_maps: both
  layer_names: [laser_layer, static_layer]