SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 5.0
  initial_epsilon: 3.0
  forward_search: false
#  primitive_filename: "/opt/ros/noetic/share/sbpl_lattice_planner/matlab/mprim/pr2.mprim"