# Traversability map filter parameters
traversability_map_filters:
  - name: surfaceNormalsFilter
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation
      output_layers_prefix: surface_normal_
      radius: 0.1
      normal_vector_positive_axis: z
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 0.5 # 0.35
      # critical_value: 1.0
#  - name: stepFilter
#    type: traversabilityFilters/StepFilter
#    params:
#      map_type: traversability_step
#      critical_value: 0.02
#      first_window_radius: 0.1
#      second_window_radius: 0.05
#      # critical_cell_number: 4
#      critical_cell_number: 4
  - name: roughnessFilter
    type: traversabilityFilters/RoughnessFilter
    params:
      map_type: traversability_roughness
      critical_value: 0.1
      estimation_radius: 0.3
  - name: weightedSumFilter
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: (1.0 / 2.0) * (traversability_slope + traversability_roughness)
#      expression: (1.0 / 3.0) * (traversability_slope + traversability_step + traversability_roughness)
  - name: deletionFilter
    type: gridMapFilters/DeletionFilter
    params:
      layers: [surface_normal_x, surface_normal_y, surface_normal_z]




#traversability_map_filters:
#  - name: surfaceNormalsFilter
#    type: gridMapFilters/NormalVectorsFilter
#    params:
#      input_layer: elevation
#      output_layers_prefix: surface_normal_
#      radius: 0.10 # 0.15
#      normal_vector_positive_axis: z
#  - name: slopeFilter
#    type: traversabilityFilters/SlopeFilter
#    params:
#      map_type: traversability_slope
#      critical_value: 0.4
#
#
#  - name: stepFilter
#    type: traversabilityFilters/StepFilter
#    params:
#      map_type: traversability_step
#      critical_value: 0.12
#      first_window_radius: 0.09
#      second_window_radius: 0.09
#      critical_cell_number: 4
#  - name: roughnessFilter
#    type: traversabilityFilters/RoughnessFilter
#    params:
#      map_type: traversability_roughness
#      critical_value: 0.06
#      estimation_radius: 0.25 # 0.1
#  - name: weightedSumFilter
#    type: gridMapFilters/MathExpressionFilters
#    params:
#      output_layer: traversability
##      expression: (1.0 / 2.0) * (traversability_roughness)
#      expression: (1.0 / 3.0) * (traversability_slope + traversability_step + traversability_roughness)
#  - name: deletionFilter
#    type: gridMapFilters/DeletionFilter
#    params:
#      layers: [surface_normal_x, surface_normal_y, surface_normal_z]